config/routes.rb
  Do512::Application.routes.draw do

  resources :events
  resources :venues
  resources :attractions

end

app/models/attraction.rb
class Attraction < ActiveRecord::Base
  attr_accessible :artist, :artistid, :billing, :event_id, :genre, :links, :sequence, :video, :image
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :additionallistingtext, :dates, :description, :eventimages, :eventname, :eventurl, :facebookeventid, :prices, :status, :tags, :videoembed
  serialize :dates
  serialize :eventimages
  serialize :prices
  has_one :venue
  has_many :attractions
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  attr_accessible :address, :city, :country, :name, :postalcode, :state, :twitterid, :venueimages, :venueurl, :venueid
  serialize :venueimages, Hash
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attractions }
    end
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
    @attraction = Attraction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attraction }
    end
  end

  # GET /attractions/new
  # GET /attractions/new.json
  def new
    @attraction = Attraction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attraction }
    end
  end

  # GET /attractions/1/edit
  def edit
    @attraction = Attraction.find(params[:id])
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = Attraction.new(params[:attraction])

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render json: @attraction, status: :created, location: @attraction }
      else
        format.html { render action: "new" }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attractions/1
  # PUT /attractions/1.json
  def update
    @attraction = Attraction.find(params[:id])

    respond_to do |format|
      if @attraction.update_attributes(params[:attraction])
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction = Attraction.find(params[:id])
    @attraction.destroy

    respond_to do |format|
      format.html { redirect_to attractions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.json
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render json: @venue, status: :created, location: @venue }
      else
        format.html { render action: "new" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.json
  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attractions/_form.html.erb
<%= form_for @attraction, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :sequence, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sequence, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :artist, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :artist, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :artistid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :artistid, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :billing, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :billing, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :genre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :genre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :links, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :links, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :event_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :event_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :video, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :video, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                attractions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<%- model_class = @attraction.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/attractions/index.html.erb
<%- model_class = Attraction.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:sequence) %></th>
      <th><%= model_class.human_attribute_name(:artist) %></th>
      <th><%= model_class.human_attribute_name(:artistid) %></th>
      <th><%= model_class.human_attribute_name(:billing) %></th>
      <th><%= model_class.human_attribute_name(:genre) %></th>
      <th><%= model_class.human_attribute_name(:links) %></th>
      <th><%= model_class.human_attribute_name(:event_id) %></th>
      <th><%= model_class.human_attribute_name(:video) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @attractions.each do |attraction| %>
      <tr>
        <td><%= link_to attraction.id, attraction_path(attraction) %></td>
        <td><%= attraction.sequence %></td>
        <td><%= attraction.artist %></td>
        <td><%= attraction.artistid %></td>
        <td><%= attraction.billing %></td>
        <td><%= attraction.genre %></td>
        <td><%= attraction.links %></td>
        <td><%= attraction.event_id %></td>
        <td><%= attraction.video %></td>
        <td><%= attraction.image %></td>
        <td><%=l attraction.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_attraction_path(attraction), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      attraction_path(attraction),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_attraction_path,
            :class => 'btn btn-primary' %>

app/views/attractions/new.html.erb
<%- model_class = @attraction.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/attractions/show.html.erb
<%- model_class = @attraction.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:sequence) %>:</strong></dt>
  <dd><%= @attraction.sequence %></dd>
  <dt><strong><%= model_class.human_attribute_name(:artist) %>:</strong></dt>
  <dd><%= @attraction.artist %></dd>
  <dt><strong><%= model_class.human_attribute_name(:artistid) %>:</strong></dt>
  <dd><%= @attraction.artistid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:billing) %>:</strong></dt>
  <dd><%= @attraction.billing %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genre) %>:</strong></dt>
  <dd><%= @attraction.genre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:links) %>:</strong></dt>
  <dd><%= @attraction.links %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_id) %>:</strong></dt>
  <dd><%= @attraction.event_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:video) %>:</strong></dt>
  <dd><%= @attraction.video %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @attraction.image %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              attractions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_attraction_path(@attraction), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              attraction_path(@attraction),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :facebookeventid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :facebookeventid, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :eventname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :eventname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :eventurl, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :eventurl, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :additionallistingtext, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :additionallistingtext, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tags, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :videoembed, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :videoembed, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dates, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :dates, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :eventimages, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :eventimages, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :prices, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :prices, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = @event.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:venue) %></th>
      <th><%= model_class.human_attribute_name(:facebookeventid) %></th>
      <th><%= model_class.human_attribute_name(:eventname) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:eventurl) %></th>
      <th><%= model_class.human_attribute_name(:additionallistingtext) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%= model_class.human_attribute_name(:videoembed) %></th>
      <th><%= model_class.human_attribute_name(:dates) %></th>
      <th><%= model_class.human_attribute_name(:eventimages) %></th>
      <th><%= model_class.human_attribute_name(:prices) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>

      <tr>
        <td><%= link_to event.id, event_path(event) %></td>
        <% if event.venue %>
          <td><%= link_to event.venue.name, venue_path(event.venue) %></td>
        <% else %>
          <td></td>
        <% end%>
        <td><%= event.facebookeventid %></td>
        <td><%= event.eventname %></td>
        <td><%= event.description %></td>
        <td><%= event.eventurl %></td>
        <td><%= event.additionallistingtext %></td>
        <td><%= event.status %></td>
        <td><%= event.tags %></td>
        <td><%= event.videoembed %></td>
        <td><%= event.dates %></td>
        <td><%= event.eventimages %></td>
        <td><%= event.prices %></td>
        <td><%=l event.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/events/new.html.erb
<%- model_class = @event.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = @event.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:facebookeventid) %>:</strong></dt>
  <dd><%= @event.facebookeventid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:eventname) %>:</strong></dt>
  <dd><%= @event.eventname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @event.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:eventurl) %>:</strong></dt>
  <dd><%= @event.eventurl %></dd>
  <dt><strong><%= model_class.human_attribute_name(:additionallistingtext) %>:</strong></dt>
  <dd><%= @event.additionallistingtext %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @event.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd><%= @event.tags %></dd>
  <dt><strong><%= model_class.human_attribute_name(:videoembed) %>:</strong></dt>
  <dd><%= @event.videoembed %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dates) %>:</strong></dt>
  <dd><%= @event.dates %></dd>
  <dt><strong><%= model_class.human_attribute_name(:eventimages) %>:</strong></dt>
  <dd><%= @event.eventimages %></dd>
  <dt><strong><%= model_class.human_attribute_name(:prices) %>:</strong></dt>
  <dd><%= @event.prices %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Do512</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/venues/_form.html.erb
<%= form_for @venue, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :venueurl, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :venueurl, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :postalcode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :postalcode, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :twitterid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :twitterid, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :venueimages, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :venueimages, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :event_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :event_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :venueid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :venueid, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                venues_path, :class => 'btn' %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<%- model_class = @venue.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/venues/index.html.erb
<%- model_class = Venue.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:venueurl) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:postalcode) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:twitterid) %></th>
      <th><%= model_class.human_attribute_name(:venueimages) %></th>
      <th><%= model_class.human_attribute_name(:event_id) %></th>
      <th><%= model_class.human_attribute_name(:venueid) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= link_to venue.id, venue_path(venue) %></td>
        <td><%= venue.name %></td>
        <td><%= venue.venueurl %></td>
        <td><%= venue.city %></td>
        <td><%= venue.state %></td>
        <td><%= venue.postalcode %></td>
        <td><%= venue.country %></td>
        <td><%= venue.address %></td>
        <td><%= venue.twitterid %></td>
        <td><%= venue.venueimages %></td>
        <td><%= venue.event_id %></td>
        <td><%= venue.venueid %></td>
        <td><%=l venue.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_venue_path(venue), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      venue_path(venue),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_venue_path,
            :class => 'btn btn-primary' %>

app/views/venues/new.html.erb
<%- model_class = @venue.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>